

    try {
        // a = 34;
        console.log(pepe);
    }
    catch (error) {
        doit(error);
    }
